INSERT INTO PAIS VALUES (1,"Colombia");
INSERT INTO PAIS VALUES (2,"Argentina");
INSERT INTO PAIS VALUES (3,"Brazil");
INSERT INTO PAIS VALUES (4,"Perú");
INSERT INTO PAIS VALUES (5,"Chile");

INSERT INTO CIUDAD VALUES (1,"Bucaramanga");
INSERT INTO CIUDAD VALUES (2,"Bogotá");
INSERT INTO CIUDAD VALUES (3,"Cali");
INSERT INTO CIUDAD VALUES (4,"Medellin");
INSERT INTO CIUDAD VALUES (5,"Cartagena");

INSERT INTO EMPRESAS VALUES (1,"Empresa1","Bucaramanga","111","SP");
INSERT INTO EMPRESAS VALUES (2,"Empresa2","Bogota","222","SS");
INSERT INTO EMPRESAS VALUES (3,"Empresa3","Cali","333","SS");
INSERT INTO EMPRESAS VALUES (4,"Empresa4","Medellin","444","SS");
INSERT INTO EMPRESAS VALUES (5,"Empresa5","Cartagena","555","SS");

INSERT INTO TIPOEMPLEADOS VALUES (111,"Daniel");
INSERT INTO TIPOEMPLEADOS VALUES (222,"Vanessa");
INSERT INTO TIPOEMPLEADOS VALUES (333,"Neyla");
INSERT INTO TIPOEMPLEADOS VALUES (444,"David");
INSERT INTO TIPOEMPLEADOS VALUES (555,"Elkin");

INSERT INTO AREAS VALUES (111,"Zona-A");
INSERT INTO AREAS VALUES (222,"Zona-B");
INSERT INTO AREAS VALUES (333,"Zona-C");
INSERT INTO AREAS VALUES (444,"Zona-D");
INSERT INTO AREAS VALUES (555,"Zona-E");

INSERT INTO PRODUCTOS VALUES (001,"Producto1",10,01,1000);
INSERT INTO PRODUCTOS VALUES (002,"Producto2",15,08,2000);
INSERT INTO PRODUCTOS VALUES (003,"Producto3",30,03,3000);
INSERT INTO PRODUCTOS VALUES (004,"Producto4",40,10,4000);
INSERT INTO PRODUCTOS VALUES (005,"Producto5",55,05,5000);