
CREATE TABLE IF NOT EXISTS `ESTUDIANTES` (
  `CODIGO` INT NOT NULL,
  `NOMBRE` VARCHAR(30),
  `DIRECCION` VARCHAR(30),
  `TELEFONO` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  PRIMARY KEY (`CODIGO`));
  
CREATE TABLE IF NOT EXISTS `MATERIAS` (
  `CODIGO_M` INT NOT NULL,
  `NOMBRE_M` VARCHAR(30),
  `CREDITOS` INT,
  `SEMESTRE` INT,
  PRIMARY KEY (`CODIGO_M`));
  
CREATE TABLE IF NOT EXISTS `DOCENTES` (
  `CODIGO_D` INT NOT NULL,
  `NOMBRE_D` VARCHAR(30),
  `TITULO` VARCHAR(30),
  `CODIGO_F` INT NOT NULL,
PRIMARY KEY (`CODIGO_D`));
  
CREATE TABLE IF NOT EXISTS `FACULTADES` (
  `CODIGO_F` INT NOT NULL,
  `NOMBRE_F` VARCHAR(30),
  `SNIES` INT,
  PRIMARY KEY (`CODIGO_F`));

CREATE TABLE IF NOT EXISTS `ESTU_MAT` (
  `NOTA` INT,
  `CODIGO` INT NOT NULL,
  `CODIGO_M` INT NOT NULL,
  `CODIGO_D` INT NOT NULL,
  PRIMARY KEY ( CODIGO , CODIGO_M , CODIGO_D ));
