ALTER TABLE  ESTU_MAT  ADD  FOREIGN KEY ( CODIGO ) REFERENCES  ESTUDIANTES  ( CODIGO ) ; 
ALTER TABLE  ESTU_MAT  ADD  FOREIGN KEY ( CODIGO_M ) REFERENCES  MATERIAS  ( CODIGO_M ) ; 
ALTER TABLE  ESTU_MAT  ADD  FOREIGN KEY ( CODIGO_D ) REFERENCES  DOCENTES  ( CODIGO_D ) ;

ALTER TABLE  DOCENTES  ADD  FOREIGN KEY ( CODIGO_F ) REFERENCES  FACULTADES  ( CODIGO_F ) ;
ALTER TABLE  DOCENTES  ADD  FOREIGN KEY ( CODIGO_U ) REFERENCES  UNIVERSIDADES  ( CODIGO_U ) ;