-- Selecciona el Nombre el estudiante, Nombre de la materia, Nombre del docente y la nota para los estudiantes de una facultad determinada(elegida por Uds de acuerdo a los inserts).

SELECT NOMBRE "Estudiante", NOMBRE_M "Materia", NOMBRE_D "Docente", NOTA "Nota", NOMBRE_F "Facultad"
FROM ESTUDIANTES E, DOCENTES D, ESTU_MAT EM,FACULTADES F, MATERIAS M
WHERE E.CODIGO = EM.CODIGO
AND D.CODIGO_D = EM.CODIGO_D
AND M.CODIGO_M = EM.CODIGO_M
AND D.CODIGO_F = 401
GROUP BY (E.NOMBRE);

-- Seleccionar los nombres de las facultades y cuantos docentes están adscritos a cada una de ellas.

SELECT NOMBRE_F "Facultad", COUNT(D.CODIGO_F ) "Cantidad de docentes"
FROM DOCENTES D, ESTU_MAT EM,FACULTADES F
WHERE D.CODIGO_F = F.CODIGO_F
AND EM.CODIGO_D = D.CODIGO_D
GROUP BY ( F.CODIGO_F);

-- Seleccionar el nombre de la facultad y el total de créditos de cada una de ellas.

SELECT F.NOMBRE_F "Facultad", F.CODIGO_F "Codigo facultad", sum(M.CREDITOS) "Creditos"
FROM FACULTADES F, MATERIAS M, DOCENTES D, ESTU_MAT EM
WHERE D.CODIGO_F = F.CODIGO_F
AND EM.CODIGO_M = M.CODIGO_M
AND EM.CODIGO_D = D.CODIGO_D
GROUP BY F.NOMBRE_F;

-- Seleccionar el código del estudiante, el nombre del estudiante y nota promedio, ordenados de forma ascendente por la nota promedio.

SELECT E.CODIGO "Codigo" , E.NOMBRE "Nombre", M.CODIGO_M "Codigo materia", avg(EM.NOTA)"Promedio nota"
FROM ESTUDIANTES E, ESTU_MAT EM, MATERIAS M
WHERE E.CODIGO = EM.CODIGO
AND EM.CODIGO_M = M.CODIGO_M
GROUP BY E.NOMBRE
ORDER BY avg(EM.NOTA) ASC;

-- EJERCICIOS PROPUESTOS -----------------------------------------

-- SELECCIONE LOS ESTUDIANTES CUYAS NOTAS SEAN MAYORES A 4, QUE NO SEAN DE LA FACULTAD DE SISTEMAS Y ORDÉNALAS DE MENOR A MAYOR

SELECT NOMBRE "Estudiante" , NOTA "Nota" , NOMBRE_F "Facultad"
FROM ESTUDIANTES E, ESTU_MAT EM, DOCENTES D, FACULTADES F
WHERE E.CODIGO = EM.CODIGO
AND D.CODIGO_D = EM.CODIGO_D
AND D.CODIGO_F = F.CODIGO_F
AND F.CODIGO_F <> 401
HAVING EM.NOTA > 40
ORDER BY EM.NOTA ASC;

-- SELECCIONE LAS MATERIAS QUE SEAN HABILITABLES, LA CANTIDAD DE ESTUDIANTES EN CADA UNA Y ORDÉNELAS DE MAYOR A MENOR

SELECT NOMBRE_M "Materia" ,COUNT(E.NOMBRE) "Cant Estudiantes"
FROM ESTU_MAT EM,MATERIAS M, ESTUDIANTES E
WHERE M.CODIGO_M = EM.CODIGO_M
AND EM.CODIGO = E.CODIGO
AND M.HABILITABLE = "S"
GROUP BY (M.CODIGO_M)
ORDER BY COUNT(E.NOMBRE) DESC;

-- SELECCIONE EL NOMBRE DE LA UNIVERSIDAD Y LA CANTIDAD DE DOCENTES QUE TIENE

SELECT NOMBRE_U "Universidad", COUNT(D.CODIGO_U) "Cantidad docentes"
FROM UNIVERSIDADES U, DOCENTES D, ESTU_MAT EM
WHERE D.CODIGO_D = EM.CODIGO_D
AND D.CODIGO_U = U.CODIGO_U
GROUP BY NOMBRE_U;

-- SELECCIONE EL NOMBRE DEL ESTUDIANTE,LA MATERIA QUE VE CADA ESTUDIANTE Y EL SEMESTRE DE FORMA ASCENDENTE

SELECT NOMBRE "Estudiante" ,NOMBRE_M "Materia", 
(SELECT SEMESTRE FROM MATERIAS M WHERE M.CODIGO_M = EM.CODIGO_M) "Semestre"
FROM MATERIAS M, ESTU_MAT EM, ESTUDIANTES E
WHERE E.CODIGO = EM.CODIGO
AND M.CODIGO_M = EM.CODIGO_M
ORDER BY (SELECT SEMESTRE FROM MATERIAS M WHERE M.CODIGO_M = EM.CODIGO_M) ASC;

-- SELECCIONE EL CÓDIGO, NOMBRE DEL ESTUDIANTE QUE ESTE EN UNA MATERIA QUE NO SEA HABILITABLE CON SU RESPECTIVA NOTA Y SEMESTRE

SELECT E.CODIGO "Codigo", E.NOMBRE "Estudiantes", M.NOMBRE_M "Materia", EM.NOTA "Nota" , M.SEMESTRE "Semestre correspondiente"
FROM ESTU_MAT EM,MATERIAS M, ESTUDIANTES E
WHERE M.CODIGO_M = EM.CODIGO_M
AND EM.CODIGO = E.CODIGO
AND M.HABILITABLE = "N"
GROUP BY M.CODIGO_M
ORDER BY E.NOMBRE;

-- SELECCIONE EL NOMBRE DE LOS ESTUDIANTES QUE ESTAN EN UNA MATERIA HABILITABLE Y SU NOTA ESTE ENTRE 30 Y 40 ORGANIZANDO DE MANERA ASCENDENTE

SELECT NOMBRE "Estudiante" , NOMBRE_M "Materia", NOTA "Nota", HABILITABLE "Habilitable"
FROM ESTUDIANTES E, ESTU_MAT EM, DOCENTES D, FACULTADES F, MATERIAS M
WHERE E.CODIGO = EM.CODIGO
AND M.CODIGO_M = EM.CODIGO_M
AND M.HABILITABLE = 'S'
AND EM.NOTA >= 30
AND EM.NOTA <= 40
GROUP BY EM.NOTA
ORDER BY EM.NOTA ASC;

-- SELECCIONE EL NOMBRE DEL DOCENTE Y SU RESPECTIVA MATERIA JUNTO CON EL CODIGO DE LA UNIVERSIDAD DONDE ESTA DICTANDO Y ORGANICE DE MANERA ASCENDENTE SEGUN EL CODIGO DE LA UNIVERSIDAD

SELECT NOMBRE_D "Docente" ,NOMBRE_M "Materia",
(SELECT CODIGO_U FROM UNIVERSIDADES U WHERE U.CODIGO_U = D.CODIGO_U) "Universidad"
FROM DOCENTES D, MATERIAS M, ESTU_MAT EM, UNIVERSIDADES U
WHERE M.CODIGO_M = EM.CODIGO_M
AND D.CODIGO_D = EM.CODIGO_D
AND D.CODIGO_U = U.CODIGO_U
ORDER BY (SELECT CODIGO_U FROM UNIVERSIDADES U WHERE U.CODIGO_U = D.CODIGO_U)ASC;