-- PERSONAS
INSERT INTO PERSONAS VALUES (123,'ELKIN','ALFREDO','ALBARRACIN','NAVAS','EAALBARR@GMAIL.COM','CRA 14 15-12') ;
INSERT INTO PERSONAS VALUES (124,'HORACIO','','GOMEZ','','HGOMEZ@GMAIL.COM','CRA 33 21-30') ;
INSERT INTO PERSONAS VALUES (125,'JOHANA','','PEREZ','RODRIGUEZ','JPEREZ@GMAIL.COM','CALLE 19 04-05') ;
INSERT INTO PERSONAS VALUES (126,'JORGE','ALIRIO','MENDOZA','','ALIRIO2084@HOTMAIL.COM','AV QUEBRADA SECA 30-23') ;
INSERT INTO PERSONAS VALUES (127,'SONIA','PAOLA','ANGARITA','PORRAS','SPANGARI@GMAIL.COM','DIAGONAL 20 56-79') ;
INSERT INTO PERSONAS VALUES (128,'PEDRO','','SUAREZ','NAVAS','PSNAVAS0920@GMAIL.COM','CRA 33 36-89') ;
INSERT INTO PERSONAS VALUES (129,'CATALINA','','ALBARRACIN','ANGARITA','CATA1526@GMAIL.COM','CALLE 36 27-08') ;
INSERT INTO PERSONAS VALUES (130,'SANTIAGO','','ALFONSO','OLARTE','SALFONSO19@YAHOO.ES','TRANVERSAL 24 17-10') ;
INSERT INTO PERSONAS VALUES (131,'JOSE','ALFREDO','VARGAS','','JAVARGAR@NOTICIAS.COM','CRA 118 20-20') ;

-- TIPO-ESTUDIOS

INSERT INTO TIPO_ESTUDIOS VALUES ( 1,'CURSO');
INSERT INTO TIPO_ESTUDIOS VALUES ( 2,'SEMINARIO');
INSERT INTO TIPO_ESTUDIOS VALUES ( 3,'DIPLOMADO');
INSERT INTO TIPO_ESTUDIOS VALUES ( 4,'PROFESIONAL');
INSERT INTO TIPO_ESTUDIOS VALUES ( 5,'ESPECIALIZACION');
INSERT INTO TIPO_ESTUDIOS VALUES ( 6,'ESPECIALIZACION TECNOLOGICA');
INSERT INTO TIPO_ESTUDIOS VALUES ( 7,'MAESTRIA');
INSERT INTO TIPO_ESTUDIOS VALUES ( 8,'DOCTORADO');
INSERT INTO TIPO_ESTUDIOS VALUES ( 9,'POSDOCTORADO');

-- ESTADO

INSERT INTO ESTADO VALUES (1,'REGISTRADO');
INSERT INTO ESTADO VALUES (2,'ACTIVO');
INSERT INTO ESTADO VALUES (3,'INACTIVO');
INSERT INTO ESTADO VALUES (4,'GRADUADO');
INSERT INTO ESTADO VALUES (5,'SIN MATRICULA');


-- INSTITUCION

INSERT INTO INSTITUCION VALUES (1,'UPB','BUCARAMANGA');
INSERT INTO INSTITUCION VALUES (2,'UPB','MEDELLIN');
INSERT INTO INSTITUCION VALUES (3,'UPB','MONTERIA');
INSERT INTO INSTITUCION VALUES (4,'UIS','BUCARAMANGA');
INSERT INTO INSTITUCION VALUES (5,'UIS','BARRANCABERMEJA');
INSERT INTO INSTITUCION VALUES (6,'UIS','SOCORRO');
INSERT INTO INSTITUCION VALUES (7,'UNAB','BUCARAMANGA');
INSERT INTO INSTITUCION VALUES (8,'UNAB','SAN GIL');
INSERT INTO INSTITUCION VALUES (9,'UNIANDES','BOGOTA');
INSERT INTO INSTITUCION VALUES (10,'U.DEL ROSARIO','BOGOTA');
INSERT INTO INSTITUCION VALUES (11,'UMB','BUCARAMANGA');
INSERT INTO INSTITUCION VALUES (12,'U.NACIONAL','BOGOTA');
INSERT INTO INSTITUCION VALUES (13,'U.NACIONAL','MEDELLIN');
INSERT INTO INSTITUCION VALUES (14,'U.EAFIT','MEDELLIN');
INSERT INTO INSTITUCION VALUES (15,'U.DEL VALLE','CALI');

-- PROGRAMAS
INSERT INTO PROGRAMAS VALUES(1,'ESP.EN GESTION DE TI',2,'7500000',5,1);
INSERT INTO PROGRAMAS VALUES(2,'ESP.EN SEGURIDAD INFORMATICA',2,'9500000',5,2);
INSERT INTO PROGRAMAS VALUES(3,'ESP.EN PROYECTOS',2,'7500000',5,3);
INSERT INTO PROGRAMAS VALUES(4,'ESP.TEC. EN NEGOCIOS',2,'4500000',6,4);
INSERT INTO PROGRAMAS VALUES(5,'ESP.TEC. EN REDES',2,'5000000',6,5);
INSERT INTO PROGRAMAS VALUES(6,'ESP.TEC. SALUD OCUPACIONAL',2,'3500000',6,6);
INSERT INTO PROGRAMAS VALUES(7,'MAESTRIA EN SISTEMAS',2,'19500000',7,7);
INSERT INTO PROGRAMAS VALUES(8,'MAESTRIA EN ELECTRONICA',2,'15000000',7,8);
INSERT INTO PROGRAMAS VALUES(9,'MAESTRIA EN ADMINISTRACION',2,'23500000',7,9);
INSERT INTO PROGRAMAS VALUES(10,'DOCTORADO EN FISICA',4,'40500000',8,10);
INSERT INTO PROGRAMAS VALUES(11,'DOCTORADO EN SISTEMAS',4,'30000000',8,11);
INSERT INTO PROGRAMAS VALUES(12,'DOCTORADO EN PROCESOS',4,'43500000',8,12);

-- PERSONAS PROGRAMAS
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(123,1,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(124,2,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(125,3,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(126,4,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(127,5,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(128,6,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(129,7,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(130,8,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(131,9,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(123,10,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(124,11,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(125,12,1,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(123,10,2,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(124,11,2,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(125,12,2,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(126,10,2,null,null);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(130,11,4,4.00,2020);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(131,11,4,3.89,2020);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(123,5,4,4.30,2020);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(124,5,4,4.00,2019);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(125,5,4,4.70,2019);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(126,8,4,4.80,2019);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(127,8,4,3.90,2020);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(128,3,4,4.80,2020);
INSERT INTO PERSONAS_PROGRAMAS VALUES 	(129,3,4,4.20,2020);









